spring:
  datasource:
    username: root
    password: progetto
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?user=root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
