spring:
  datasource:
    username: root
    password: progetto
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/?user=root

#Specifica per hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect



  #Specifica per la sicurezza

#DA RISOLVERE
 # security:
#    oauth2:
 #     resourceserver:
 #       jwt:
 #         issuer-uri: http://localhost:8080/auth

